---
TENANT_B:
  mac_vrf_id_base: 10000
  pseudowire_rt_base: 1000
  point_to_point_services:
    - name: TEN_A_site1_site2_eline
      type: vpws-pseudowire
      subinterfaces:
        - number: 10
      endpoints:
        - id: 52
          nodes: ["PE-01"]
          interfaces: ["Ethernet3"]
        - id: 53
          nodes: ["PE-04"]
          interfaces: ["Ethernet3"]