---
TENANT_A:
  vrfs:
    TENANT_A_WAN:
      vrf_id: 10
      address_families:
        - vpn-ipv4
      l3_interfaces:
        - description: "L3vpn service, vlan 100"
          interfaces: [ Ethernet3.100 ]
          encapsulation_dot1q_vlan: [ 100 ]
          enabled: true
          mtu: 9000
          ip_addresses: [ 10.10.100.2/24 ]
          nodes: [ PE-01 ]
        - description: "L3vpn service, vlan 200"
          interfaces: [ Ethernet3.200 ]
          encapsulation_dot1q_vlan: [ 200 ]
          enabled: true
          mtu: 9000
          ip_addresses: [ 10.10.200.2/24 ]
          nodes: [ PE-04 ]
      bgp_peers:
        10.10.100.1:
          description: CPE-01
          remote_as: 65001
          password: $1c$/ei4LgYRVQVyaE3DDcjbXw==
          send_community: standard
          nodes: [ PE-01 ]
          default_originate:
            always: true
        10.10.200.1:
          description: CPE-02
          remote_as: 65005
          password: $1c$/ei4LgYRVQVyaE3DDcjbXw==
          send_community: standard
          nodes: [ PE-04 ]
          default_originate:
            always: true
