---

# Backone Interfaces

core_interfaces:
  p2p_links_ip_pools:
    - name: underlay_pool
      ipv4_pool: 100.64.48.0/24
  p2p_links_profiles:
    - name: default_bb_profile
      # speed: "forced 40gfull"
      mtu: 9000
      isis_hello_padding: true
      isis_metric: 10
      ip_pool: underlay_pool
      isis_circuit_type: level-1-2
      ipv6_enable: true
  p2p_links:

    # P-01 Links
    - nodes: [ P-01, P-02 ]
      id: 1
      interfaces: [ Ethernet1, Ethernet1 ]
      profile: default_bb_profile
    - nodes: [ P-01, PE-01 ]
      id: 2
      interfaces: [ Ethernet3, Ethernet1 ]
      profile: default_bb_profile
    - nodes: [ P-01, PE-02 ]
      id: 3
      interfaces: [ Ethernet2, Ethernet2 ]
      profile: default_bb_profile
    - nodes: [ P-01, PE-03 ]
      id: 4
      speed: "forced 100gfull"
      interfaces: [ Ethernet4, Ethernet1 ]
      profile: default_bb_profile

    # P-02 Links
    - nodes: [ P-02, PE-02 ]
      id: 5
      interfaces: [ Ethernet2, Ethernet1 ]
      profile: default_bb_profile
    - nodes: [ P-02, PE-03 ]
      id: 6
      interfaces: [ Ethernet5, Ethernet2 ]
      profile: default_bb_profile
    - nodes: [ P-02, PE-04 ]
      id: 7
      interfaces: [ Ethernet3, Ethernet1 ]
      profile: default_bb_profile
    - nodes: [ P-02, PE-04 ]
      id: 8
      interfaces: [ Ethernet4, Ethernet2 ]
      profile: default_bb_profile

    # PE-01 Links
    - nodes: [ PE-01, PE-02 ]
      id: 9
      interfaces: [ Ethernet2, Ethernet3 ]
      profile: default_bb_profile

